import localFont from "next/font/local";
import "./globals.css";
import Footer from "./Components/Common/Footer";
import Header from "./Components/Common/Header";

import { Inter } from "next/font/google";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata = {
  title: "Finance Department, Government of the Gilgit Baltistan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`font-inter`}>
      <body className={`antialiased`}>
        <div className="relative">
          <Header />
          <main className="bg-white">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
