import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Components/Common/Header";
import Footer from "./Components/Common/footer/Footer";
import AuthProvider from "./providers/SessionProvider";

// Configure Inter font with specific weights
const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata = {
  title: "Finance Department, Government of the Gilgit Baltistan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Header />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
